StylesPath = .vale/styles
Packages = proselint, alex
Vocab = XJustiz-Converter

[formats]
ts = md

[!{*.{lock,json,jsonc,yaml,yml,dic,aff},*.gitignore,LICENSE,CODE_OF_CONDUCT.md,*/template.md,*.dsl,.vale.ini,.vale/styles/*}]
BasedOnStyles = Vale, proselint, alex

[*.ts]
BasedOnStyles = Vale, proselint, alex
# Ignore TSDoc tags like `@param`.
TokenIgnores = (@[a-zA-Z]+\s+)\S+
# Fix ignoring Markdown codeblock fences.
BlockIgnores = (?s)(```.*?```)
